#!/bin/bash

# this script will setup postfix email system

# checks if postfix is isntalled or not, if not they prompt for installation.
sudo systemctl status postfix &> /dev/null && echo "Postfix is running, setting up the postfix configuration"

if ! sudo systemctl status postfix &> /dev/null ; then
        echo "Postfix is not installed"
        read -p "Do you want to install Postfix? [yes/no] " ans
        if [ $ans = yes ]; then
                sudo apt install postfix -y
        else
                echo "Cancelling the installation."
                exit 1
        fi

fi
sleep 1

# this will remove all the older sasl passwd in order to setup new one.

sudo rm -rf /etc/postfix/sasl/sasl_passwd /etc/postfix/sasl/sasl_passwd/db
sudo touch /etc/postfix/sasl/sasl_passwd

# asks for email and password that is used to setup postfix, email password can be generated by google.com
# please do not use main gmail password for the server.

read -p "Please enter the email and password here: [example.com:passwd] " pass
        sudo echo "[smtp.gmail.com]:587 $pass" > /etc/postfix/sasl/sasl_passwd
        echo "Setting up email..."

# this encryptes and changes the files mode to 600 which mean only root can read the provided sasl passwd and passwd.db

        sudo postmap /etc/postfix/sasl/sasl_passwd
        sudo chmod 600 /etc/postfix/sasl/sasl_passwd /etc/postfix/sasl/sasl_passwd.db

# checks if the main.cf contains the required value, if not then inserts the value without replicating multiple time

        grep -q "# Enable SASL authentification
smtp_sasl_auth_enable = yes
smtp_sasl_security_options = noanonymous
smtp_sasl_password_maps = hash:/etc/postfix/sasl/sasl_passwd
smtp_tls_security_level = encrypt
smtp_tls_CAfi1e = /etc/ssl/certs/ca-certificates.crt" /etc/postfix/main.cf ||sudo echo "# Enable SASL authentification
smtp_sasl_auth_enable = yes
smtp_sasl_security_options = noanonymous
smtp_sasl_password_maps = hash:/etc/postfix/sasl/sasl_passwd
smtp_tls_security_level = encrypt
smtp_tls_CAfi1e = /etc/ssl/certs/ca-certificates.crt" >> /etc/postfix/main.cf

sleep 1
# replace the value inside main.cf wihtout replicating multiple time

sudo sed -i '/^relayhost/ s/.*/relayhost = [smtp.gmail.com]:587/' /etc/postfix/main.cf && echo "Setup was comeplete, restarting postfix.."

# after finishing the stup this will restart the postfix service

sudo systemctl restart postfix
sleep 1

# shows the example of usage

echo "Postfix restated.
use >>sendmail <example.com> to send email"
echo "example of script sending email: >>> echo -e "Subject: Backup Notification\n\n <linux-command>" | sendmail example@gmail.com &> /dev/null"

# script exits with exit code 0
exit 0
